[package]
name = "protoc-gen-prost-validate"
version = "0.0.1"
authors = ["Marcus Griep <marcus@griep.us>"]
description = "Coming soon…"
license = "Apache-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
